[package]
name = "pycomfy"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
comfy-table = "7.0"

[package.metadata.maturin]
name = "pycomfy"
