base_cols:
  - tag
  - author
  - title
  - journal
  - create
  - hash

date_fields:
  - create
  - mod
  - access 

default_date_field: mod

bang_field: author
recent_field: create

fuzzy:
  fields:
    - author
    - title
  limit: 10
  score_col_name: score
