base_cols:
  - tag
  - author
  - title
  - journal

date_fields:
  - year

default_date_field: year
bang_field: author
recent_field: year

fuzzy:
  fields:
    - author
    - title
  limit: 50
  score_col_name: score
